[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 11520077
upload_speed  = 921600

; Librería ESP32-audioI2S (schreibfaul1)
; https://github.com/schreibfaul1/ESP32-audioI2S
lib_deps =
        https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
