[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 11520077
upload_speed  = 921600

; Librería ESP32-audioI2S (schreibfaul1)
; https://github.com/schreibfaul1/ESP32-audioI2S
lib_deps =
    schreibfaul1/ESP32-audioI2S @ ^2.0.0

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
